const LOG_LABELS = {
    APP_START: 'APP_START',
    RABBIT_ERROR: 'RABBIT_ERROR',
};
const HTTP_CODE = {
    OK: 200,
    CREATED: 201,
    NO_CONTENT: 204,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    PAYMENT_REQUIRED: 402,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    UNPROCESSABLE_ENTITY: 422,
    INTERNAL_SERVER_ERROR: 500,
};


export {
    LOG_LABELS,
    HTTP_CODE,
};
